services:

  afk-game:
    build: .
    container_name: afk-game
  
    
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/tmp/runtime-root
  
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
  
    devices:
      - /dev/video0:/dev/video0
  
    privileged: true
  
    network_mode: host
  
    stdin_open: true
    tty: true

